---

# Audio-related tasks.

- name: Install pipewire package
  ansible.builtin.package:
    name: "{{ xrdp_pipewire_package_name }}"
    state: present

- name: Install xrdp pipewire module
  ansible.builtin.apt:
    name: "{{ xrdp_pipewire_module_name }}"
    default_release: "{% if ansible_facts['distribution_major_version'] == '12' %}bookworm-backports{% endif %}"
    state: present
